### ISSUE TITLE
development ceased?

### ISSUE THREAD

**Issue by cmeesters** [amc-heme/cellranger-snakemake-gke#1]
Hi,

have you been following up on the project? Would be nice to know.

Cheers
Christian

**Comment by jairav** [comment]
Working on it! There are a couple of obstacles, primarily Snakemake 8's GCS plugin doesn't [work](https://github.com/snakemake/snakemake-storage-plugin-gcs/issues/18), but once thats fixed we should be able to move along.

**Comment by cmeesters** [comment]
Ah, thanks. Good to here!

I wasn't aware of this issue. NB: I hope using gcs is an optional feature.

**Comment by jairav** [comment]
@cmeesters We have decided to temporarily cease development on this in favor of pursing using Snakemake 8 (and its Google Batch feature), with a containerized version of cellranger. No timeline on that though. This repo will probably be deleted/archived shortly.
